# Generated by Django 3.2.9 on 2021-11-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='OutputDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_device_model', to='control.roommodel')),
            ],
            options={
                'verbose_name_plural': 'Output Devices',
                'db_table': 'output_device',
            },
        ),
        migrations.CreateModel(
            name='InputDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('data', models.CharField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_device_model', to='control.roommodel')),
            ],
            options={
                'verbose_name_plural': 'Input Devices',
                'db_table': 'input_device',
            },
        ),
    ]
