# Generated by Django 3.2.9 on 2021-11-27 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False, null=True)),
                ('type', models.CharField(choices=[('lamp', 'Lamp'), ('fan', 'Fan'), ('humidity', 'Humidity'), ('temperature', 'Temperature')], max_length=15)),
                ('data', models.CharField(max_length=255, null=True)),
                ('info', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_model', to='control.roommodel')),
            ],
            options={
                'verbose_name_plural': 'Input Devices',
                'db_table': 'devices ',
            },
        ),
        migrations.RemoveField(
            model_name='outputdevicemodel',
            name='room',
        ),
        migrations.DeleteModel(
            name='InputDeviceModel',
        ),
        migrations.DeleteModel(
            name='OutputDeviceModel',
        ),
    ]
